// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	game.proto
	login.proto

It has these top-level messages:
	ClosePush
	RoomListReq
	RoomListRes
	EnterRoomReq
	ExitRoomReq
	RegisterReq
	RegisterRes
	LoginReq
	LoginRes
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ClosePush_Code int32

const (
	ClosePush_REPEATED ClosePush_Code = 0
	ClosePush_INNER    ClosePush_Code = 1
)

var ClosePush_Code_name = map[int32]string{
	0: "REPEATED",
	1: "INNER",
}
var ClosePush_Code_value = map[string]int32{
	"REPEATED": 0,
	"INNER":    1,
}

func (x ClosePush_Code) Enum() *ClosePush_Code {
	p := new(ClosePush_Code)
	*p = x
	return p
}
func (x ClosePush_Code) String() string {
	return proto.EnumName(ClosePush_Code_name, int32(x))
}
func (x *ClosePush_Code) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClosePush_Code_value, data, "ClosePush_Code")
	if err != nil {
		return err
	}
	*x = ClosePush_Code(value)
	return nil
}

// 服务器关闭连接推送
type ClosePush struct {
	Code             *ClosePush_Code `protobuf:"varint,1,req,name=code,enum=msg.ClosePush_Code" json:"code,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ClosePush) Reset()         { *m = ClosePush{} }
func (m *ClosePush) String() string { return proto.CompactTextString(m) }
func (*ClosePush) ProtoMessage()    {}

func (m *ClosePush) GetCode() ClosePush_Code {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ClosePush_REPEATED
}

// 房间列表请求
type RoomListReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RoomListReq) Reset()         { *m = RoomListReq{} }
func (m *RoomListReq) String() string { return proto.CompactTextString(m) }
func (*RoomListReq) ProtoMessage()    {}

// 房间列表响应
type RoomListRes struct {
	Rooms            []*RoomListRes_RoomInfo `protobuf:"bytes,1,rep,name=rooms" json:"rooms,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *RoomListRes) Reset()         { *m = RoomListRes{} }
func (m *RoomListRes) String() string { return proto.CompactTextString(m) }
func (*RoomListRes) ProtoMessage()    {}

func (m *RoomListRes) GetRooms() []*RoomListRes_RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type RoomListRes_RoomInfo struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	PlayerNum        *int32 `protobuf:"varint,2,req,name=player_num" json:"player_num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RoomListRes_RoomInfo) Reset()         { *m = RoomListRes_RoomInfo{} }
func (m *RoomListRes_RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomListRes_RoomInfo) ProtoMessage()    {}

func (m *RoomListRes_RoomInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RoomListRes_RoomInfo) GetPlayerNum() int32 {
	if m != nil && m.PlayerNum != nil {
		return *m.PlayerNum
	}
	return 0
}

// 进入房间请求
type EnterRoomReq struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EnterRoomReq) Reset()         { *m = EnterRoomReq{} }
func (m *EnterRoomReq) String() string { return proto.CompactTextString(m) }
func (*EnterRoomReq) ProtoMessage()    {}

func (m *EnterRoomReq) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 退出房间请求
type ExitRoomReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ExitRoomReq) Reset()         { *m = ExitRoomReq{} }
func (m *ExitRoomReq) String() string { return proto.CompactTextString(m) }
func (*ExitRoomReq) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("msg.ClosePush_Code", ClosePush_Code_name, ClosePush_Code_value)
}
