// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RegisterRes_Code int32

const (
	RegisterRes_YES   RegisterRes_Code = 0
	RegisterRes_NO    RegisterRes_Code = 1
	RegisterRes_EXIST RegisterRes_Code = 2
)

var RegisterRes_Code_name = map[int32]string{
	0: "YES",
	1: "NO",
	2: "EXIST",
}
var RegisterRes_Code_value = map[string]int32{
	"YES":   0,
	"NO":    1,
	"EXIST": 2,
}

func (x RegisterRes_Code) Enum() *RegisterRes_Code {
	p := new(RegisterRes_Code)
	*p = x
	return p
}
func (x RegisterRes_Code) String() string {
	return proto.EnumName(RegisterRes_Code_name, int32(x))
}
func (x *RegisterRes_Code) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegisterRes_Code_value, data, "RegisterRes_Code")
	if err != nil {
		return err
	}
	*x = RegisterRes_Code(value)
	return nil
}

type LoginRes_Code int32

const (
	LoginRes_YES       LoginRes_Code = 0
	LoginRes_NO        LoginRes_Code = 1
	LoginRes_NOT_EXIST LoginRes_Code = 2
	LoginRes_PASS_ERR  LoginRes_Code = 3
)

var LoginRes_Code_name = map[int32]string{
	0: "YES",
	1: "NO",
	2: "NOT_EXIST",
	3: "PASS_ERR",
}
var LoginRes_Code_value = map[string]int32{
	"YES":       0,
	"NO":        1,
	"NOT_EXIST": 2,
	"PASS_ERR":  3,
}

func (x LoginRes_Code) Enum() *LoginRes_Code {
	p := new(LoginRes_Code)
	*p = x
	return p
}
func (x LoginRes_Code) String() string {
	return proto.EnumName(LoginRes_Code_name, int32(x))
}
func (x *LoginRes_Code) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LoginRes_Code_value, data, "LoginRes_Code")
	if err != nil {
		return err
	}
	*x = LoginRes_Code(value)
	return nil
}

// 注册请求
type RegisterReq struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}

func (m *RegisterReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

// 注册响应
type RegisterRes struct {
	Code             *RegisterRes_Code `protobuf:"varint,1,req,name=code,enum=msg.RegisterRes_Code" json:"code,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RegisterRes) Reset()         { *m = RegisterRes{} }
func (m *RegisterRes) String() string { return proto.CompactTextString(m) }
func (*RegisterRes) ProtoMessage()    {}

func (m *RegisterRes) GetCode() RegisterRes_Code {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return RegisterRes_YES
}

// 登录请求
type LoginReq struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}

func (m *LoginReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

// 登录响应
type LoginRes struct {
	Code             *LoginRes_Code `protobuf:"varint,1,req,name=code,enum=msg.LoginRes_Code" json:"code,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}

func (m *LoginRes) GetCode() LoginRes_Code {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return LoginRes_YES
}

func init() {
	proto.RegisterEnum("msg.RegisterRes_Code", RegisterRes_Code_name, RegisterRes_Code_value)
	proto.RegisterEnum("msg.LoginRes_Code", LoginRes_Code_name, LoginRes_Code_value)
}
